### ISSUE TITLE
Logging to RO file system

### ISSUE THREAD

**Issue by joelwking** [joelwking/prezo#2]
If you specify a log destination to a read-only file system, an uncaught exception is thrown:

```
root@564e2c3773a6:/prezo# python3 library/upload.py 
Traceback (most recent call last):
  File "library/upload.py", line 30, in <module>
    log = logger.Logger(**opts).setup()
  File "/prezo/library/logger/logger.py", line 51, in setup
    fh = logging.FileHandler(self.file_name)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/opt/powerpoint/log'
```

**Comment by joelwking** [comment]
If you log to a directory which does not exist, you also encounter an exception.
